# Mqtt Manager
keys:
  #client types
  sender: "/Users/cole/PycharmProjects/ObjectDectectApp/assets/configs/mqtt_clients/mqtt_client_sender.yaml"
  logger: "/Users/cole/PycharmProjects/ObjectDectectApp/assets/configs/mqtt_clients/mqtt_client_logger.yaml"
type: "MqttManager"